baseurl = "https://github.com/panjf2000/panjf2000.github.io"
#baseurl = ""
theme = "dimension"
#defaultContentLanguage = "zh"
languageCode = "zh-cn"
title = "潘建锋 | Mind Seeker"
enableRobotsTXT = true
disableKinds=["RSS"]
hasCJKLanguage = true 
enableEmoji = true
googleAnalytics = "UA-123-45"

#[languages]
#[languages.zh]
#  languageCode = "zh-cn"
#  languageName = "Chinese"
#  weight = 1
#[languages.en]
#  languageCode = "en-us"
#  languageName = "English"
#  weight = 2
#  title = "Personal Website for Andy Pan"

[params]
  subtitle = ""
  author = "Andy Pan"
  description = '<!--[--><We laughed and kept saying "see u soon",
but inside we both knew we would never see each other again.!--]-->'
#  logo = "fa-diamond"
  logoimage = "images/pan.png"
  copyright = "Powered by 潘建锋,All rights reserved - 2019"

[[params.social]]
  medium = "博客"
  icon = "myblog"
  link = "https://taohuawu.club"

[[params.social]]
  medium = "知乎"
  icon = "zhihu"
  link = "https://www.zhihu.com/people/andy_pan"

[[params.social]]
  medium = "微博"
  icon = "weibo"
  link = "https://weibo.com/Matrigram"

[[params.social]]
  medium = "开源中国"
  icon = "osc"
  link = "https://my.oschina.net/osandy"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/panjf2000"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "http://www.linkedin.com/in/andy-pan-7b1227115/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/panjf2000/"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/andy.pan.jianfeng"
  
[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/_andy_pan"

[[params.social]]
  medium = "豆瓣"
  icon = "douban"
  link = "https://www.douban.com/people/114345322/"

#[[params.social]]
#  medium = "tumblr"
#  icon = "tumblr"
#  link = "https://andy-pan-1573.tumblr.com/"

