baseurl = "https://andypan.site"
theme = "dimension"
#defaultContentLanguage = "zh"
languageCode = "en-us"
title = "Andy Pan"
enableRobotsTXT = true
disableKinds=["RSS"]
hasCJKLanguage = true 
enableEmoji = true
googleAnalytics = "UA-123-45"

#[languages]
#[languages.zh]
#  languageCode = "zh-cn"
#  languageName = "Chinese"
#  weight = 1
#[languages.en]
#  languageCode = "en-us"
#  languageName = "English"
#  weight = 2
#  title = "Personal Website for Andy Pan"

[params]
  subtitle = "Never say never"
  author = "Andy Pan"
  description = 'Live fast. Die young. Be wild. Have fun.'
#  logo = "fa-diamond"
  logoimage = "images/avatar.png"
  copyright = "Powered by Andy Pan, All rights reserved @ 2020"

#[[params.social]]
#  medium = "Blog"
#  icon = "myblog"
#  link = "https://taohuawu.club"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/panjf2000"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/_andy_pan"

#[[params.social]]
#  medium = "Linkedin"
#  icon = "linkedin"
#  link = "http://www.linkedin.com/in/andy-pan-7b1227115/"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/panjf2000/"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/andy.pan.jianfeng"
  
[[params.social]]
  medium = "Zhihu"
  icon = "zhihu"
  link = "https://www.zhihu.com/people/andy_pan"

[[params.social]]
  medium = "Weibo"
  icon = "weibo"
  link = "https://weibo.com/Matrigram"

[[params.social]]
  medium = "OS China"
  icon = "osc"
  link = "https://my.oschina.net/osandy"

[[params.social]]
  medium = "Douban"
  icon = "douban"
  link = "https://www.douban.com/people/114345322/"
